services:
  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:9000
    depends_on:
      - backend
